POST http://localhost:8080/api/pizza
Content-Type: application/json

{
  "name": "chilis",
  "description": "chilis pizza",
  "value": "1500"
}

###

PUT http://localhost:8080/api/pizza
Content-Type: application/json

{
  "id": 10,
  "name": "chilis",
  "description": "nagyon chilis pizza",
  "value": "1500"
}

###
GET http://localhost:8080/api/pizza
Accept: application/json

###

DELETE http://localhost:8080/api/pizza/7
Accept: application/json

###


